sibia/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("account/", include("account.urls")),
    path("Naku-One-Africa/", include("nakuoneafrica.urls")),
    path("summernote/", include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Tab/Site Title
admin.site.site_header = "Sibia Africa"

admin.site.index_title = "Sibia Africa - Admin"

website/urls.py
from django.urls import path
from .views import index, about, contact, newsletter_subscription, help, request_appointment
from .crud_methods import edit_homepage

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("request-appointment/", request_appointment, name="request_appointment"),
    path("edit/homepage/<int:pk>/", edit_homepage, name="edit_homepage"),
    path("help/", help, name="help"),
    path("newsletter-subscription/", newsletter_subscription, name="newsletter_subscription"),
]

website/models.py
from django.db import models


class NewsletterSubscription(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Homepage(models.Model):
    hero_title = models.CharField(max_length=150, blank=True, null=True)
    hero_paragraph = models.TextField(blank=True, null=True)
    hero_primary_btn = models.CharField(max_length=90, blank=True, null=True)
    hero_secondary_btn = models.CharField(max_length=90, blank=True, null=True)
    hero_image = models.FileField(
        upload_to="homepage/", blank=True, null=True)
    quote = models.TextField(blank=True, null=True)
    feature_1_title = models.CharField(max_length=150, blank=True, null=True)
    feature_1_paragraph = models.TextField(blank=True, null=True)
    feature_1_btn = models.CharField(max_length=50, blank=True, null=True)
    feature_2_title = models.CharField(max_length=150, blank=True, null=True)
    feature_2_paragraph = models.TextField(blank=True, null=True)
    feature_2_btn = models.CharField(max_length=50, blank=True, null=True)
    feature_3_title = models.CharField(max_length=150, blank=True, null=True)
    feature_3_paragraph = models.TextField(blank=True, null=True)
    feature_3_btn = models.CharField(max_length=50, blank=True, null=True)
    feature_4_title = models.CharField(max_length=150, blank=True, null=True)
    feature_4_paragraph = models.TextField(blank=True, null=True)
    feature_4_btn = models.CharField(max_length=50, blank=True, null=True)
    features_image = models.FileField(
        upload_to="homepage/", blank=True, null=True)
    newsletter_subscription = models.CharField(
        max_length=200, blank=True, null=True)
    about_title = models.CharField(max_length=150, blank=True, null=True)
    about_paragraph = models.TextField(blank=True, null=True)
    about_primary_btn = models.CharField(max_length=90, blank=True, null=True)
    about_image = models.ImageField(
        upload_to="homepage/", blank=True, null=True)
    cta = models.CharField(max_length=90, blank=True, null=True)

    def __str__(self):
        return "Home Page"

    class Meta:
        verbose_name = "Home Page"
        verbose_name_plural = "Home Page"


class PrivacyPolicy(models.Model):
    icon = models.CharField(max_length=60, blank=True, null=True)
    title = models.CharField(max_length=150, blank=True, null=True)
    paragraph = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Privacy Policy"
        verbose_name_plural = "Privacy Policies"


class TermsOfService(models.Model):
    icon = models.CharField(max_length=60, blank=True, null=True)
    title = models.CharField(max_length=150, blank=True, null=True)
    paragraph = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Terms Of Service"
        verbose_name_plural = "Terms Of Services"


class FrequentlyAskedQuestion(models.Model):
    question = models.TextField(blank=True, null=True)
    answer = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = "Frequently Asked Question"
        verbose_name_plural = "Frequently Asked Questions"


class Help(models.Model):
    title = models.CharField(max_length=150, blank=True, null=True)
    paragraph = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Help"


class Appointment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}'s Appointment"

website/forms.py
from django import forms
from .models import NewsletterSubscription, Homepage, Appointment


class NewsletterSubscriptionForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscription
        fields = ['email']


class HomepageForm(forms.ModelForm):
    class Meta:
        model = Homepage
        fields = ('__all__')


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'name',
            'email',
            'phone',
            'message',
        ]

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from .forms import NewsletterSubscriptionForm, AppointmentForm
from .models import Homepage, PrivacyPolicy, TermsOfService, FrequentlyAskedQuestion, Help


def index(request):

    try:
        homepage_data = Homepage.objects.first()

        if not homepage_data:
            raise ValueError("No Homeage object found.")

        context = {
            "homepage_data": homepage_data,
            "title_tag": "Revolutionizing Community Healthcare with AI",
            "meta_description": "Sibia integrates a community health hospital, SDG research center, and advanced medical AI to serve informal communities with personalized therapies, illness control, and predictive analytics.",
            "meta_keywords": "Sibia, community healthcare, medical AI, SDG research, personalized therapies, illness control, predictive analytics, healthcare solutions, sustainable development goals",
        }

        return render(request, "index.html", context)

    except Homepage.DoesNotExist:
        return HttpResponse("Homeage not found.", status=404)

    except Exception as e:
        return HttpResponse("An error occurred while processing the request.", status=500)


def about(request):
    context = {
        "title_tag": "About Us",
    }
    return render(request, "about.html", context)


def contact(request):
    context = {
        "title_tag": "Contact Us",
    }
    return render(request, "contact.html", context)


def newsletter_subscription(request):
    if request.method == 'POST':
        form = NewsletterSubscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Thank you for subscribing")
            return redirect('index')
    else:
        form = NewsletterSubscriptionForm()
    return render(request, 'index.html', {'form': form})


def help(request):
    try:
        faq_data = get_object_or_404(Help, pk=1)
    except:
        faq_data = None

    try:
        privacy_policy_data = get_object_or_404(Help, pk=2)
    except:
        privacy_policy_data = None

    try:
        terms_of_service_data = get_object_or_404(Help, pk=3)
    except:
        terms_of_service_data = None

    if privacy_policy_data:
        privacy_policy_title = privacy_policy_data.title
        privacy_policy_paragraph = privacy_policy_data.paragraph
    else:
        privacy_policy_title = "Privacy Policy for Sibia"
        privacy_policy_paragraph = 'Thank you for choosing to be part of our community at Sibia ("Company, " "we, " "us, " "our"). We are committed to protecting your personal information and your right to privacy.'

    if faq_data:
        faq_title = faq_data.title
        faq_paragraph = faq_data.paragraph
    else:
        faq_title = "Frequently Asked Questions"
        faq_paragraph = "These are general questions we get time to time. Contact us if you cant find the answers you're looking for"

    if terms_of_service_data:
        terms_of_service_title = terms_of_service_data.title
        terms_of_service_paragraph = terms_of_service_data.paragraph
    else:
        terms_of_service_title = "Terms of Service"
        terms_of_service_paragraph = "These Terms of Service govern your use of Sibia. By accessing or using our website, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use our website."

    context = {
        "title_tag": "Help Centre",
        "policies": PrivacyPolicy.objects.all(),
        "terms_of_services": TermsOfService.objects.all(),
        "frequently_asked_questions": FrequentlyAskedQuestion.objects.all(),
        "faq_title": faq_title,
        "faq_paragraph": faq_paragraph,
        "privacy_policy_title": privacy_policy_title,
        "privacy_policy_paragraph": privacy_policy_paragraph,
        "terms_of_service_title": terms_of_service_title,
        "terms_of_service_paragraph": terms_of_service_paragraph,
    }
    return render(request, "help.html", context)


def request_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Appointment confirmed! We have received your request and will contact you shortly with the details. Thank you for your trust.")
            return redirect('index')
    else:
        form = AppointmentForm()

    return render(request, 'contact.html', {'form': form})

website/templates/about.html
{% extends 'base.html' %}{% load static %} {% block body %}
<header class="container-fluid">
    <h1 class="display-2 text-center">About Us</h1>
</header>
<main class="container-xxl">
    <div class="container">
        <h1 class="display-4 fw-bold">Sibia is a community health hospital, an SDG research centre, and state-of-the-art medical AI combined into one facility that is intended to serve informal communities. We address important healthcare issues by utilising AI and data analytics to provide personalised therapies, illness control, and predictive analytics. Working together with leading medical professionals and researchers, Sibia is dedicated to improving community health and accomplishing sustainable development objectives. Examine the all-inclusive solutions we offer to learn more about how we're changing things.</h1>
    </div>
</main>
{% endblock %}

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% include "head.html" %}
    </head>
    <body class="bg-light">
        {% include "navbar.html" %}
        <main style="padding-top: 6rem;">
            {% include "messages.html" %}
            {% block body %} {% endblock %}
        </main>
        {% include "footer.html" %}
        {% include "modals/request_appointment.html" %}
        {% include "modals/login.html" %}
        {% include "modals/loading_spinner.html" %}
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="{% static 'js/loadingSpinner.js' %}"></script>
        <script src="{% static 'js/footerYear.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

website/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<header class="container-fluid">
    <h1 class="display-2 text-center">Contact Us</h1>
</header>
<main class="container-xxl">
    <div class="container">
        <h1 class="display-4 fw-bold">Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore assumenda excepturi molestias nam cupiditate fuga quos deserunt, repellat quidem beatae dolor sit qui doloremque? Beatae delectus quidem, officia dolorum, aliquam perferendis vero voluptates cum reprehenderit voluptatibus unde dolor, quos cumque.</h1>
    </div>
</main>
{% endblock %}

website/templates/footer.html
<div class="container-fluid text-brown">
    <div class="container border-top pt-3">
        <footer class="py-5">
            <div class="row">
                <div class="col-6 col-md-2 mb-3">
                    <h5 class="font-alt">Sibia Africa</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="{% url 'index' %}" class="nav-link p-0 text-body-secondary">Home</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'help' %}" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'about' %}" class="nav-link p-0 text-body-secondary">About Us</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'contact' %}" class="nav-link p-0 text-body-secondary">Contact Us</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">AI & Data</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5 class="font-alt">Naku-One Africa</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Media</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Podcast</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Library</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Services</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Research</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5 class="font-alt">Betty Care Clinic</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Location</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Patient Guide</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Community Health</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'help' %}" class="nav-link p-0 text-body-secondary">Appointment FAQs</a></li>
                    </ul>
                </div>

                <div class="col-md-5 offset-md-1 mb-3">
                    <form action="{% url 'newsletter_subscription' %}" method="POST" onsubmit="showSpinner()">
                        {% csrf_token %}
                        <h5 class="font-alt">Subscribe to our newsletter</h5>
                        <p>Monthly digest of what's new and exciting from us.</p>
                        <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                            <label for="email" class="visually-hidden">Email address</label>
                            <input required class="form-control me-2" name="email" id="email" type="email" placeholder="Email address" data-sb-validations="required,email" />
                            <button class="btn btn-primary submit-btn" type="submit">Subscribe</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p id="footer-year"></p>
                <ul class="list-unstyled d-flex">
                    <li>Follow Sibia Africa</li>
                    <li class="ms-3"><a class="link-body-emphasis" href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="#"><i class="fa-brands fa-x-twitter"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="#"><i class="fa-brands fa-youtube"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="#"><i class="fa-brands fa-instagram"></i></a></li>
                </ul>
            </div>
        </footer>
    </div>
</div>

website/templates/head.html
{% load static %}
<!-- Meta Tags -->
<title>{{ title_tag }} - Sibia Africa</title>
<meta name="author" content="Sibia Africa" />
<meta name="description" content="{{ meta_description|safe }}" />
<meta name="keywords" content="{{ meta_keywords }}" />
{% if meta_thumbnail %}
<meta name="image" content="https://sibia.africa{{ meta_thumbnail }}">
{% else %}
<meta name="image" content="https://sibia.africa{% static 'sibia_meta_thumbnail.jpg' %}">
{% endif %}
<meta name="robots" content="index, follow">
<link rel="canonical" href="{{ meta_url }}">

<!-- Facebook Meta Tags -->
<meta property="og:locale" content="en_EU">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ title_tag }} - Sibia Africa">
<meta property="og:description" content="{{ meta_description|safe }}">
<meta property="og:keywords" content="{{ meta_keywords }}">
<meta property="og:url" content="{{ meta_url }}">
<meta property="og:site_name" content="Sibia Africa">
{% if meta_thumbnail %}
<meta property="og:image" content="https://sibia.africa{{ meta_thumbnail }}">
{% else %}
<meta property="og:image" content="https://sibia.africa{% static 'sibia_meta_thumbnail.jpg' %}">
{% endif %}
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ title_tag }} - Sibia Africa">
<meta name="twitter:description" content="{{ meta_description|safe }}">
{% if meta_thumbnail %}
<meta name="twitter:image" content="https://sibia.africa{{ meta_thumbnail }}">
{% else %}
<meta name="twitter:image" content="https://sibia.africa{% static 'sibia_meta_thumbnail.jpg' %}">
{% endif %}
<meta name="twitter:image:width" content="1200">
<meta name="twitter:image:height" content="600">
<meta name="twitter:url" content="{{ meta_url }}">
<meta name="twitter:site" content="www.sibia.africa">
<meta name="twitter:creator" content="@sibia.africa">

<!-- LinkedIn Meta Tags -->
{% if meta_thumbnail %}
<meta property="og:image" content="https://sibia.africa{{ meta_thumbnail }}">
{% else %}
<meta property="og:image" content="https://sibia.africa{% static 'sibia_meta_thumbnail.jpg' %}">
{% endif %}
<meta property="og:image:alt" content="{{ meta_description|safe }}">
<meta property="linkedin:site" content="https://www.linkedin.com/company/sibia/">

<!-- Favicons Start -->
<link rel="icon" type="image/icon" href="{% static 'favicon/favicon.ico' %}" />
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}" />
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/android-chrome-512x512.png' %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/android-chrome-192x192.png' %}" />
<!-- Favicons End -->

<!-- Manifest -->
<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}" />

<!-- Fontawesome CDN -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"/>

<!-- FONT AWESOME -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

<!-- MAIN FONT -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">

<!-- css -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

website/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<header class="masthead">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <!-- Mashead text and app badges-->
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
                    <h1 class="display-1 fs-heading text-brown lh-1 mb-3">{{ homepage_data.hero_title }}</h1>
                    <p class="lead text-muted mb-5">{{ homepage_data.hero_paragraph }}</p>
                    <div class="d-flex flex-column flex-lg-row align-items-center">
                        <a class="btn btn-primary me-lg-3 mb-4 mb-lg-0" href="#!">{{ homepage_data.hero_primary_btn }}</a>
                        <a class="btn btn-outline-primary" href="#!">{{ homepage_data.hero_secondary_btn }}</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="masthead-device-mockup">
                    <img src="{{ homepage_data.hero_image.url }}" alt="" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Quote/testimonial aside-->
<aside class="text-center bg-brown">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-xl-8">
                <div class="text-white mb-4"><h2 class="font-alt">{{ homepage_data.quote }}</h2></div>
            </div>
        </div>
    </div>
</aside>
<!-- App features section-->
<section id="features">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-8 order-lg-1 mb-5 mb-lg-0">
                <div class="container-fluid px-5">
                    <div class="row gx-5">
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-start">
                                <i class="bi-camera icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">{{ homepage_data.feature_1_title }}</h3>
                                <p class="text-muted">{{ homepage_data.feature_1_paragraph }}</p>
                                <a href="" class="text-secondary">{{ homepage_data.feature_1_btn }}</a>
                            </div>
                        </div>
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-start">
                                <i class="bi-phone icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">{{ homepage_data.feature_2_title }}</h3>
                                <p class="text-muted">{{ homepage_data.feature_2_paragraph }}</p>
                                <a href="" class="text-secondary">{{ homepage_data.feature_2_btn }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-5 mb-md-0">
                            <!-- Feature item-->
                            <div class="text-start">
                                <i class="bi-gift icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">{{ homepage_data.feature_3_title }}</h3>
                                <p class="text-muted">{{ homepage_data.feature_3_paragraph }}</p>
                                <a href="" class="text-secondary">{{ homepage_data.feature_3_btn }}</a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <!-- Feature item-->
                            <div class="text-start">
                                <i class="bi-patch-check icon-feature text-gradient d-block mb-3"></i>
                                <h3 class="font-alt">{{ homepage_data.feature_4_title }}</h3>
                                <p class="text-muted">{{ homepage_data.feature_4_paragraph }}</p>
                                <a href="" class="text-secondary">{{ homepage_data.feature_4_btn }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 order-lg-0">
                <img src="{{ homepage_data.features_image.url }}" alt="" class="img-fluid">
            </div>
        </div>
    </div>
</section>
<!-- subscription badge section-->
<section class="bg-brown" id="download">
    <div class="container px-5">
        <h2 class="text-center text-white font-alt mb-4">{{ homepage_data.newsletter_subscription }}</h2>
        <div class="d-flex flex-column flex-lg-row align-items-center justify-content-center">
            <form action="{% url 'newsletter_subscription' %}" method="POST" onsubmit="showSpinner()">
                {% csrf_token %}
                <div class="d-flex flex-row form-group">
                    <label for="id_email" class="visually-hidden">Email address</label>
                    <input required class="form-control me-2" name="email" id="id_email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                    <input type="submit" value="Submit" name="newsletter_subscription" class="btn btn-outline-light submit-btn" id="id_newsletter_subscription">
                </div>
            </form>
        </div>
    </div>
</section>
<!-- Basic features section-->
<section class="bg-light">
    <div class="container px-5">
        <div class="row g-5 align-items-center justify-content-center justify-content-lg-between">
            <div class="col-sm-12 col-lg-5">
                <h2 class="display-5 text-brown fs-heading lh-1 mb-4">{{ homepage_data.about_title }}</h2>
                <p class="lead text-muted">{{ homepage_data.about_paragraph }}</p>
                <a class="my-4 lead" href="{% url 'about' %}">{{ homepage_data.about_primary_btn }} <i class="fa-solid fa-chevron-right"></i></a>
            </div>
            <div class="col-sm-12 col-lg-5">
                <img class="img-fluid rounded-4" src="{{ homepage_data.about_image.url }}" />
            </div>
        </div>
    </div>
</section>
<!-- Call to action section-->
<section class="cta bg-primary">
    <div class="cta-content">
        <div class="container px-5">
            <h2 class="text-white fs-heading display-1 lh-1 mb-4">{{ homepage_data.cta|safe|linebreaks }}</h2>
        </div>
    </div>
</section>
{% endblock %}

website/templates/messages.html
{% for message in messages %}
<section class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</section>
{% endfor %}